<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DigbyswiftUmbracoCountryPickerContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\Digbyswift.Umbraco.CountryPicker\**\*.*</DigbyswiftUmbracoCountryPickerContentFilesPath>
  </PropertyGroup>

  <Target Name="CopyDigbyswiftUmbracoCountryPickerAssets" BeforeTargets="Build">
    <ItemGroup>
      <DigbyswiftUmbracoCountryPickerContentFiles Include="$(DigbyswiftUmbracoCountryPickerContentFilesPath)" />
    </ItemGroup>
    <Message Text="Copying Digbyswift.Umbraco.CountryPicker files: $(DigbyswiftUmbracoCountryPickerContentFilesPath) - #@(DigbyswiftUmbracoCountryPickerContentFiles->Count()) files" Importance="high" />
    <Copy
      SourceFiles="@(DigbyswiftUmbracoCountryPickerContentFiles)"
      DestinationFiles="@(DigbyswiftUmbracoCountryPickerContentFiles->'$(MSBuildProjectDirectory)\App_Plugins\Digbyswift.Umbraco.CountryPicker\%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

  <Target Name="ClearDigbyswiftUmbracoCountryPickerAssets" BeforeTargets="Clean">
    <ItemGroup>
      <DigbyswiftUmbracoCountryPickerDir Include="$(MSBuildProjectDirectory)\App_Plugins\Digbyswift.Umbraco.CountryPicker\" />
    </ItemGroup>
    <Message Text="Clear old Digbyswift.Umbraco.CountryPicker data" Importance="high" />
    <RemoveDir Directories="@(DigbyswiftUmbracoCountryPickerDir)" />
  </Target>
</Project>
