<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Include="package.json" />
      <None Include="tsconfig.json" />
    </ItemGroup>

    <Target Name="BuildCountryPickerFrontend" BeforeTargets="Build">
        <Message Text="Building CountryPicker frontend" Importance="high" />
        <Exec WorkingDirectory="$(MSBuildProjectDirectory)"
              Command="npm ci"
              Condition="!Exists('$(MSBuildProjectDirectory)\node_modules') And Exists('$(MSBuildProjectDirectory)\package-lock.json')" />
        <Exec WorkingDirectory="$(MSBuildProjectDirectory)"
              Command="npm install"
              Condition="!Exists('$(MSBuildProjectDirectory)\node_modules') And !Exists('$(MSBuildProjectDirectory)\package-lock.json')" />
        <Exec WorkingDirectory="$(MSBuildProjectDirectory)"
              Command="npm run build" />
    </Target>

<!--    <Target Name="ExcludeCountryPickerTypeScriptFromPackage"-->
<!--            BeforeTargets="Build">-->
<!--        <ItemGroup>-->
<!--            <Content Remove="**\appsettings-schema.Umbraco.Cms.json;**\*schema.json;**\tsconfig.json;**\*.ts;**\*.tsx;**\*.tsbuildinfo;**\*.map" />-->
<!--            <None Remove="**\appsettings-schema.Umbraco.Cms.json;**\*schema.json;**\tsconfig.json;**\*.ts;**\*.tsx;**\*.tsbuildinfo;**\*.map" />-->
<!--            <Compile Remove="**\appsettings-schema.Umbraco.Cms.json;**\*schema.json;**\tsconfig.json;**\*.ts;**\*.tsx;**\*.tsbuildinfo;**\*.map" />-->
<!--            <_PackageFiles Remove="**\appsettings-schema.Umbraco.Cms.json;**\*schema.json;**\tsconfig.json;**\*.ts;**\*.tsx;**\*.tsbuildinfo;**\*.map" />-->
<!--        </ItemGroup>-->
<!--    </Target>-->

</Project>
